# Generated by Django 3.0.7 on 2020-06-21 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200620_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='customer1',
            new_name='customers',
        ),
    ]
