# Generated by Django 3.0.7 on 2020-06-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200621_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasheet',
            old_name='desciption',
            new_name='description',
        ),
    ]
